name: Node.js CI

on:
  push:
    branches: [ master, devops]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install -g yarn 
          yarn install
      - name: build
        run: yarn run build
      - name: test
        # run: npm test
        run: echo "fake test"
      - name: create infrastructure
        # run: npm test
        run: echo "fake test"
      - name: upload to s3
        # run: npm test
        run: echo "fake test"